config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'application#index'
  resources :projects do
    resources :tasks, only: [:create, :edit, :update, :destroy]
  end
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base

  has_many :project_tasks, inverse_of: :task
  has_many :projects, through: :project_tasks

  belongs_to :user

  validates :name, presence: true

  def self.overdue
    self.all.where('completed = ? AND DATE(complete_by) < ?', false, Date.today)
  end

  def self.completed
    self.all.where('completed = ?', true)
  end

  def self.not_completed
    self.all.where('completed = ?', false)
  end

  def self.due_today
    self.all.where('completed = ? AND DATE(complete_by) = ?', false, Date.today)
  end

  def add_project(project)
    projects << project if project && !projects.include?(project)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :ensure_logged_in
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  #Check to see if we are in a nested url and set the project if we are
  before_action :set_project, only: [:edit, :update, :destroy, :create]

  def index
    case params[:filter]
    when "overdue"
      @tasks = current_user.tasks.overdue
    when "completed"
      @tasks = current_user.tasks.completed
    when "not_completed"
      @tasks = current_user.tasks.not_completed
    when "due_today"
      @tasks = current_user.tasks.due_today
    else
        @tasks = current_user.tasks
    end

    respond_to do |format|
      format.html
      format.json { render :json => @tasks }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @task }
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    #rails includes a blank project_id for some reason
    if (@project || params[:task][:project_ids].count > 1) && @task.save
      @task.add_project(@project)
      @project ? render(json: @task) : redirect_to(task_path(@task))
    else
      @task.errors[:projects] << 'must contain at least one project' if params[:task][:project_ids] && params[:task][:project_ids].count < 2
      @project ? redirect_to(project_path(@project)) : render("new")
    end
  end

  def update
    #raise params.inspect
    #rails includes a blank project_id for some reason
    if params[:task][:project_ids].count > 1 && @task.update(task_params)
      @project_task.update(project_task_params) if @project && @project_task
      @project ? redirect_to(project_path(@project)) : redirect_to(task_path(@task))
    else
      @task.errors[:projects] << 'must contain at least one project' unless params[:task][:project_ids].count > 1
      render "edit"
    end
  end

  def destroy
    if !@project || @task.projects.count < 2
      @task.delete
    else
      @project.tasks.delete(@task)
    end
    @project ? render(status: 200) : redirect_to(tasks_path)
  end

  private
  def task_params
    params.require(:task).permit(:name, :description, :complete_by, :completed, project_ids: [])
  end

  def project_task_params
    params.require(:project_task).permit(:priority)
  end

  def set_task
    @task = current_user.tasks.find_by(id: params[:id])
    render status: :not_found, text: 'The requested task does not exist or was created by a different user.' if !@task
  end

  def set_project
    #Simply behave as if the project is not there if for some reason we can't find it
    #this should never happen and should not matter if it does
    @project = current_user.projects.find_by(id: params[:project_id])
    @project_task = @project.project_tasks.find_by(task_id: @task.id) if @task && @project
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def days_from_today(date)
    return '' if !date
    days = date.jd - Date.today.jd
    label = pluralize(days.abs, "day")
    if days < 0
      return "#{label} ago"
    elsif days > 0
      return "in #{label}"
    else
      return "today"
    end
  end

  def task_classes(task)
    classes = ['list-group-item']
    classes << 'task-completed' if task.completed
    if !task.completed && task.complete_by
      classes << 'task-overdue' if task.complete_by.jd < Date.today.jd
      classes << 'task-warning' if task.complete_by.jd == Date.today.jd
    end
    return classes
  end

  def task_form(project, task)
    if project
      return form_for [project, task] {|f| yield(f)}
    else
      return form_for [task] {|f| yield(f)}
    end
  end
end

app/views/tasks/_form.html.erb
<% if current_user.projects.count < 1 %>
  <div class="alert alert-warning" role="alert">
    You must have at least one project to create a task. Click
    <%= link_to "here", new_project_path, class: 'alert-link' %> to create a project.
  </div>
<% end %>
<%= task_form project, task do |f| %>
  <%= render partial: 'application/form_errors', locals: {object: task} %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <% if project_task %>
    <div class="form-group">
      <% #I regret nothing %>
      <%= label_tag 'project_task_priority', 'Project Specific Priority' %>
      <%= number_field_tag "project_task[priority]", project_task.priority, class: 'form-control', id: 'project_task_priority', min: -1000, max: 1000 %>
      <small id="emailHelp" class="form-text text-muted">Projects with higher priority will show up at the top of the list (Only applies to this project).</small>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :complete_by %>
    <%= f.date_field :complete_by, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.check_box :completed%>
    <%= f.label :completed%>
  </div>
  <div class="form-group">
    <%= f.label :projects, "Select one or more projects to add this task to" %>
    <ul class="list-group">
      <%= f.collection_check_boxes :project_ids, current_user.projects, :id, :name do |b| %>
        <%= b.label(class: "list-group-item") do %>
          <%= b.check_box %>
          <%= b.text %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/tasks/_task.html.erb
<% project||=nil #Make sure project is defined so we dont get an error %>
<%= content_tag :li, class: task_classes(task), title: task.description do %>
  <%= link_to task.name, task_path(task)%>
  <%if project %>
    <%= link_to project_task_path(project, task), class: 'btn btn-danger task-list-btn', method: 'delete' do%>
      <span class="glyphicon glyphicon-minus"></span>
    <% end %>
    <%= link_to edit_project_task_path(project, task), class: 'btn btn-default task-list-btn' do %>
      <span class="glyphicon glyphicon-edit"></span>
    <% end %>
  <% end %>
  <span class="complete-by"><%= days_from_today(task.complete_by) %></span>

<% end %>

app/views/tasks/edit.html.erb
<%= render partial: 'form', locals: {task: @task, project: @project, project_task: @project_task} %>

app/views/tasks/index.html.erb
<div class="clearfix">
  <h2 class="inline">Tasks</h2>
  <select class="right" name="filter" id="filter">
    <option value="all">All</option>
    <option value="overdue">Overdue</option>
    <option value="due_today">Due Today</option>
    <option value="completed">Completed</option>
    <option value="not_completed">Not Completed</option>
  </select>
</div>
<ul class="list-group" id="tasks-list">
  Loading tasks...
</ul>

<script>
  $(function(){
    loadTasksIndex($('#filter').val());
    $('#filter').change(function(){
      loadTasksIndex($(this).val());
    });
  });
</script>

app/views/tasks/new.html.erb
<%= render partial: 'form', locals: {task: @task, project: nil, project_task: nil} %>

app/views/tasks/show.html.erb
<div class="clearfix">
  <h2 class="inline"><%= @task.name %></h2>
  <%= link_to "Edit", edit_task_path(@task), id: 'edit-task', class: 'btn btn-default right'%>
</div>
<p>
  <% if @task.completed %>
    <span class="task-completed-lbl completed">Completed</span>
  <% else %>
    <span class="task-completed-lbl">Not Completed</span>
  <% end %>
  <span class="complete-by"><%= days_from_today(@task.complete_by) %></span>
</p>
<p><%= @task.description %></p>
<h3>In projects:</h3>
<ul class="list-group">
  <%= render @task.projects %>
</ul>
<%= link_to "Delete", task_path(@task), method: 'delete', id: 'delete-task', class: 'btn btn-danger'%>